# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queryserver', '0003_auto_20160207_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='box',
            name='videoid',
        ),
        migrations.RemoveField(
            model_name='object',
            name='sessionid',
        ),
        migrations.RemoveField(
            model_name='query',
            name='sessionid',
        ),
        migrations.RemoveField(
            model_name='session',
            name='socid',
        ),
        migrations.RemoveField(
            model_name='video',
            name='socid',
        ),
        migrations.AddField(
            model_name='box',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queryserver.Object'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queryserver.Video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queryserver.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queryserver.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='soc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queryserver.Soc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='soc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queryserver.Soc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='xlen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='ylen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soc',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
