# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryserver', '0006_box_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='color',
            field=models.CharField(default='#FF0000', max_length=10),
        ),
    ]
